name: Publish Kev's Docker image

on:
  push: #git command to run action
    branches: [main]  # brach of focus
    workflow-dispatch: #added

jobs:
  push_to_kmiregistry: #edited job title
    name: Push Kev's Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - run: echo "Kev's message"
        # - name: Check out the repo
        # uses: actions/checkout@v2

      - name: Set up QEMU #Emulation support tool for using workflow
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx #Tool for creating and booting a builder. Do not need to use actions/checkout@v2 thanks to this.
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Kev's Docker image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:3120-cicd-iwatsukikevin/dockerbuild/Dockerfile"
          push: true
          tags: iwatsukikevin/kmirepo:latest

      - run: ls
      - run: echo "end of workflow"
